//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.NewProjectTemplate.Contracts.ModelMetadata.Security;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class UserMetadata
{
	public const int DisplayNameMaxLength = 100;
	public const int EmailMaxLength = 255;
	public const int NormalizedEmailMaxLength = 255;
	public const int NormalizedUsernameMaxLength = 50;
	public const int PasswordHashMaxLength = Int32.MaxValue;
	public const int SecurityStampMaxLength = 255;
	public const int UsernameMaxLength = 50;
}
