//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Havit.NewProjectTemplate.Model.Metadata.Security
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public static class UserMetadata
	{
		public const int DisplayNameMaxLength = 100;
		public const int EmailMaxLength = 255;
		public const int NormalizedEmailMaxLength = 255;
		public const int NormalizedUsernameMaxLength = 50;
		public const int PasswordHashMaxLength = 2147483647;
		public const int SecurityStampMaxLength = 255;
		public const int UsernameMaxLength = 50;
	}
}