//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.NewProjectTemplate.Contracts.ModelMetadata.Localizations;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class LanguageMetadata
{
	public const int CultureMaxLength = 10;
	public const int NameMaxLength = 200;
	public const int UiCultureMaxLength = 10;
}
