//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.Patterns.DataEntries;

namespace Havit.GoranG3.DataLayer.DataEntries.Common
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public interface IApplicationSettingsEntries : IDataEntries
	{
		Havit.GoranG3.Model.Common.ApplicationSettings Current { get; }
			
	}
}