//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.NewProjectTemplate.DataLayer.DataEntries.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public interface IApplicationSettingsEntries : Havit.Data.Patterns.DataEntries.IDataEntries
{
	Havit.NewProjectTemplate.Model.Common.ApplicationSettings Current { get; }
}
