//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.Patterns.DataSources;

namespace Havit.NewProjectTemplate.DataLayer.DataSources.Security;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public interface IRoleDataSource : IDataSource<Havit.NewProjectTemplate.Model.Security.Role>
{
}
