//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.Repositories;

namespace Havit.GoranG3.DataLayer.DataEntries.Localizations
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class LanguageEntries : DataEntries<Havit.GoranG3.Model.Localizations.Language>, ILanguageEntries 
	{
		public Havit.GoranG3.Model.Localizations.Language Czech
        {
            get
            {
				if (czech == null)
				{
					czech = GetEntry(Havit.GoranG3.Model.Localizations.Language.Entry.Czech);
				}
				return czech;
            }
        }
		private Havit.GoranG3.Model.Localizations.Language czech;

		public Havit.GoranG3.Model.Localizations.Language English
        {
            get
            {
				if (english == null)
				{
					english = GetEntry(Havit.GoranG3.Model.Localizations.Language.Entry.English);
				}
				return english;
            }
        }
		private Havit.GoranG3.Model.Localizations.Language english;

		public LanguageEntries(IRepository<Havit.GoranG3.Model.Localizations.Language> repository)
			: base(repository)
		{
		}
	}
}