//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.Repositories;

namespace Havit.GoranG3.DataLayer.DataEntries.Projects
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class ProjectEntries : DataEntries<Havit.GoranG3.Model.Projects.Project>, IProjectEntries 
	{
		public Havit.GoranG3.Model.Projects.Project Root
        {
            get
            {
				if (root == null)
				{
					root = GetEntry(Havit.GoranG3.Model.Projects.Project.Entry.Root);
				}
				return root;
            }
        }
		private Havit.GoranG3.Model.Projects.Project root;

		public ProjectEntries(Havit.GoranG3.DataLayer.Repositories.Projects.IProjectRepository repository)
			: base(repository)
		{
		}
	}
}