//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.NewProjectTemplate.DataLayer.DataSources.Common.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class FakeDateInfoDataSource : FakeDataSource<Havit.NewProjectTemplate.Model.Common.DateInfo>, Havit.NewProjectTemplate.DataLayer.DataSources.Common.IDateInfoDataSource
	{
		public FakeDateInfoDataSource(params Havit.NewProjectTemplate.Model.Common.DateInfo[] data)
			: this((IEnumerable<Havit.NewProjectTemplate.Model.Common.DateInfo>)data)
		{			
		}

		public FakeDateInfoDataSource(IEnumerable<Havit.NewProjectTemplate.Model.Common.DateInfo> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}