//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.NewProjectTemplate.Contracts.ModelMetadata.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public static class CountryMetadata
{
	public const int IsoCodeMaxLength = 2;
	public const int IsoCode3MaxLength = 3;
	public const int PhoneCountryCodeMaxLength = 6;
}
