//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Havit.GoranG3.Model.Metadata.HumanResources
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public static class EmployeeMetadata
	{
		public const int BirthNumberMaxLength = 15;
		public const int FirstNameMaxLength = 50;
		public const int LastNameMaxLength = 50;
		public const int NoteMaxLength = 0;
		public const int TitlePrefixMaxLength = 20;
		public const int TitleSuffixMaxLength = 20;
	}
}