//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.GoranG3.DataLayer.DataSources.Crm.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class FakeBusinessCaseDataSource : FakeDataSource<Havit.GoranG3.Model.Crm.BusinessCase>, Havit.GoranG3.DataLayer.DataSources.Crm.IBusinessCaseDataSource
	{
		public FakeBusinessCaseDataSource(params Havit.GoranG3.Model.Crm.BusinessCase[] data)
			: this((IEnumerable<Havit.GoranG3.Model.Crm.BusinessCase>)data)
		{			
		}

		public FakeBusinessCaseDataSource(IEnumerable<Havit.GoranG3.Model.Crm.BusinessCase> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}