//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Havit.NewProjectTemplate.Model.Metadata.Crm
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public static class ContactMetadata
	{
		public const int CompanyRegistrationNumberMaxLength = 15;
		public const int EmailMaxLength = 200;
		public const int MobileMaxLength = 20;
		public const int NameMaxLength = 200;
		public const int PhoneMaxLength = 20;
		public const int TaxRegistrationNumberMaxLength = 15;
		public const int WebMaxLength = 200;
	}
}