//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.Repositories;

namespace Havit.GoranG3.DataLayer.DataEntries.Finance
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class TransactionItemTypeEntries : DataEntries<Havit.GoranG3.Model.Finance.TransactionItemType>, ITransactionItemTypeEntries 
	{
		public Havit.GoranG3.Model.Finance.TransactionItemType Cost
        {
            get
            {
				if (cost == null)
				{
					cost = GetEntry(Havit.GoranG3.Model.Finance.TransactionItemType.Entry.Cost);
				}
				return cost;
            }
        }
		private Havit.GoranG3.Model.Finance.TransactionItemType cost;

		public Havit.GoranG3.Model.Finance.TransactionItemType Revenue
        {
            get
            {
				if (revenue == null)
				{
					revenue = GetEntry(Havit.GoranG3.Model.Finance.TransactionItemType.Entry.Revenue);
				}
				return revenue;
            }
        }
		private Havit.GoranG3.Model.Finance.TransactionItemType revenue;

		public TransactionItemTypeEntries(Havit.GoranG3.DataLayer.Repositories.Finance.ITransactionItemTypeRepository repository)
			: base(repository)
		{
		}
	}
}