//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns.DataSources.Fakes;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Havit.Data.Patterns.Attributes;

namespace Havit.NewProjectTemplate.DataLayer.DataSources.Attrida.Fakes
{
	[Fake]
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class FakeAttridaCommentDataSource : FakeDataSource<Havit.NewProjectTemplate.Model.Attrida.AttridaComment>, Havit.NewProjectTemplate.DataLayer.DataSources.Attrida.IAttridaCommentDataSource
	{
		public FakeAttridaCommentDataSource(params Havit.NewProjectTemplate.Model.Attrida.AttridaComment[] data)
			: this((IEnumerable<Havit.NewProjectTemplate.Model.Attrida.AttridaComment>)data)
		{			
		}

		public FakeAttridaCommentDataSource(IEnumerable<Havit.NewProjectTemplate.Model.Attrida.AttridaComment> data, ISoftDeleteManager softDeleteManager = null)
			: base(data, softDeleteManager)
		{
		}
	}
}