//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.Repositories;

namespace Havit.GoranG3.DataLayer.DataEntries.HumanResources
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class TeamEntries : DataEntries<Havit.GoranG3.Model.HumanResources.Team>, ITeamEntries 
	{
		public Havit.GoranG3.Model.HumanResources.Team Everyone
        {
            get
            {
				if (everyone == null)
				{
					everyone = GetEntry(Havit.GoranG3.Model.HumanResources.Team.Entry.Everyone);
				}
				return everyone;
            }
        }
		private Havit.GoranG3.Model.HumanResources.Team everyone;

		public TeamEntries(IRepository<Havit.GoranG3.Model.HumanResources.Team> repository)
			: base(repository)
		{
		}
	}
}