//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Havit.GoranG3.Model.Metadata.Attrida
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public static class AttridaDocumentMetadata
	{
		public const int DescriptionMaxLength = 100;
		public const int OriginalFilenameMaxLength = 200;
		public const int StorageFilenameMaxLength = 200;
	}
}