//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Havit.NewProjectTemplate.DataLayer.DataEntries.Security;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public class RoleEntries : Havit.Data.Patterns.DataEntries.DataEntries<Havit.NewProjectTemplate.Model.Security.Role>, IRoleEntries 
{
	private Havit.NewProjectTemplate.Model.Security.Role systemAdministrator;
	private Havit.NewProjectTemplate.Model.Security.Role userSettingsAdministrator;

	public Havit.NewProjectTemplate.Model.Security.Role SystemAdministrator => systemAdministrator ??= GetEntry(Havit.NewProjectTemplate.Model.Security.Role.Entry.SystemAdministrator);
	public Havit.NewProjectTemplate.Model.Security.Role UserSettingsAdministrator => userSettingsAdministrator ??= GetEntry(Havit.NewProjectTemplate.Model.Security.Role.Entry.UserSettingsAdministrator);

	public RoleEntries(Havit.NewProjectTemplate.DataLayer.Repositories.Security.IRoleRepository repository)
		: base(repository)
	{
	}
}
