//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Havit.Data.EntityFrameworkCore.Patterns;
using Havit.Data.Patterns.DataEntries;
using Havit.Data.Patterns.Repositories;

namespace Havit.GoranG3.DataLayer.DataEntries.Security
{
	[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
	public class RoleEntries : DataEntries<Havit.GoranG3.Model.Security.Role>, IRoleEntries 
	{
		public Havit.GoranG3.Model.Security.Role SystemAdministrator
        {
            get
            {
				if (systemAdministrator == null)
				{
					systemAdministrator = GetEntry(Havit.GoranG3.Model.Security.Role.Entry.SystemAdministrator);
				}
				return systemAdministrator;
            }
        }
		private Havit.GoranG3.Model.Security.Role systemAdministrator;

		public Havit.GoranG3.Model.Security.Role UserSettingsAdministrator
        {
            get
            {
				if (userSettingsAdministrator == null)
				{
					userSettingsAdministrator = GetEntry(Havit.GoranG3.Model.Security.Role.Entry.UserSettingsAdministrator);
				}
				return userSettingsAdministrator;
            }
        }
		private Havit.GoranG3.Model.Security.Role userSettingsAdministrator;

		public RoleEntries(Havit.GoranG3.DataLayer.Repositories.Security.IRoleRepository repository)
			: base(repository)
		{
		}
	}
}