//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.EntityFrameworkCore.Patterns.Repositories;
using Havit.Data.EntityFrameworkCore.Patterns.SoftDeletes;
using Microsoft.EntityFrameworkCore;
using DbContext = Havit.Data.EntityFrameworkCore.DbContext;

namespace Havit.NewProjectTemplate.DataLayer.Repositories.Common;

internal class CountryDbRepositoryQueryProvider : IRepositoryQueryProvider<Havit.NewProjectTemplate.Model.Common.Country, System.Int32>
{
	private readonly Func<DbContext, System.Int32, Havit.NewProjectTemplate.Model.Common.Country> _getObjectQuery;
	private readonly Func<DbContext, System.Int32, CancellationToken, Task<Havit.NewProjectTemplate.Model.Common.Country>> _getObjectAsyncQuery;
	private readonly Func<DbContext, System.Int32[], IEnumerable<Havit.NewProjectTemplate.Model.Common.Country>> _getObjectsQuery;
	private readonly Func<DbContext, System.Int32[], IAsyncEnumerable<Havit.NewProjectTemplate.Model.Common.Country>> _getObjectsAsyncQuery;

	public CountryDbRepositoryQueryProvider()
	{
		_getObjectQuery = EF.CompileQuery((DbContext dbContext, System.Int32 id) => dbContext
			.Set<Havit.NewProjectTemplate.Model.Common.Country>()
			.TagWith("CountryDbRepository.GetObject")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32 id, CancellationToken cancellationToken) => dbContext
			.Set<Havit.NewProjectTemplate.Model.Common.Country>()
			.TagWith("CountryDbRepository.GetObjectAsync")
			.Where(entity => entity.Id == id)
			.FirstOrDefault());

		_getObjectsQuery = EF.CompileQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<Havit.NewProjectTemplate.Model.Common.Country>()
			.TagWith("CountryDbRepository.GetObjects")
			.Where(entity => ids.Contains(entity.Id)));

		_getObjectsAsyncQuery = EF.CompileAsyncQuery((DbContext dbContext, System.Int32[] ids) => dbContext
			.Set<Havit.NewProjectTemplate.Model.Common.Country>()
			.TagWith("CountryDbRepository.GetObjectsAsync")
			.Where(entity => ids.Contains(entity.Id)));
	}

	public Func<DbContext, System.Int32, Havit.NewProjectTemplate.Model.Common.Country> GetGetObjectQuery() => _getObjectQuery;
	public Func<DbContext, System.Int32, CancellationToken, Task<Havit.NewProjectTemplate.Model.Common.Country>> GetGetObjectAsyncQuery() => _getObjectAsyncQuery;
	public Func<DbContext, System.Int32[], IEnumerable<Havit.NewProjectTemplate.Model.Common.Country>> GetGetObjectsQuery() => _getObjectsQuery;
	public Func<DbContext, System.Int32[], IAsyncEnumerable<Havit.NewProjectTemplate.Model.Common.Country>> GetGetObjectsAsyncQuery() => _getObjectsAsyncQuery;
}
