//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Havit.Data.Patterns.Repositories;

namespace Havit.NewProjectTemplate.DataLayer.Repositories.Common;

[System.CodeDom.Compiler.GeneratedCode("Havit.Data.EntityFrameworkCore.CodeGenerator", "1.0")]
public partial interface ICountryRepository : IRepository<Havit.NewProjectTemplate.Model.Common.Country>
{
}
